services:
  - type: web
    name: bookstar-backend
    env: docker
    region: frankfurt
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
      - key: MAIL_HOST
      - key: MAIL_PORT
      - key: MAIL_USERNAME
      - key: MAIL_PASSWORD
