spring:
  application:
    name: rating-books
  datasource:
    url: jdbc:h2:mem:booksdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

