spring:
  application:
    name: BookStar
  mvc:
    servlet:
      path: /bookstar
  datasource:
    url: jdbc:h2:mem:bookstar_k6db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: dummy
    password: dummy
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  sql:
    init:
      mode: always
server:
  port: 8086
