server:
  port: ${PORT:8080}         # Render inyecta PORT, si no está usa 8080
  address: 0.0.0.0
spring:
  application:
    name: BookStar
  mvc:
    servlet:
      path: /bookstar
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookstar}
    username: ${SPRING_DATASOURCE_USERNAME:bookuser}
    password: ${SPRING_DATASOURCE_PASSWORD:bookpass}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:b8a87ed6ed3563}
    password: ${MAIL_PASSWORD:15b85ecad199f7}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: false
  sql:
    init:
      mode: always
logging:
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  metrics:
    enable:
      method:
        timed: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
