spring:
  application:
    name: BookStar
  mvc:
    servlet:
      path: /bookstar
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstar
    username: bookuser
    password: bookpass
    driver-class-name: org.postgresql.Driver
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b8a87ed6ed3563
    password: 15b85ecad199f7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: false
  sql:
    init:
      mode: always
logging:
  file:
    name: logs/app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  metrics:
    enable:
      method:
        timed: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
