spring:
  application:
    name: BookStar
  mvc:
    servlet:
      path: /bookstar
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstar
    username: bookuser
    password: bookpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.security: DEBUG
