global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bookstar'
    metrics_path: '/bookstar/actuator/prometheus'  # ✅ include servlet path
    static_configs:
      - targets: ['host.docker.internal:8080']
